# ????
server:
  port: 8080

spring:
  #redis
  redis:
    port: 6379
    host: 8.137.91.234
    password: 123456
    timeout: 10000
    database: 2
    lettuce:
      pool:
        max-active: 8 #最大连接数量
        max-idle: 8 #最大空闲连接数
        min-idle: 0 #最小空闲连接数
        max-wait: 100ms #最大等待时间

  #??????
  mail:
    #??smtp??????
    # qq???smtp.qq.com          ???465?587
    # sina    smtp.sina.cn
    # aliyun  smtp.aliyun.com
    # 163     smtp.163.com       ???465?994
    host: smtp.qq.com
    #?????
    username: 2270851619@qq.com
    #????,?????????????????????
    password: fpowciodpvbudhhi
    #???465?587
    port: 587
    #????????UTF-8
    default-encoding: UTF-8
    #????
    properties:
      mail:
        #??SSL ????
        smtp:
          ssl:
            #????????ssl
            enable: false
            required: false
          #??debug??????????????????????????????
        debug: false
  #??????
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath\:/META-INF/resources/,classpath\:/resources/,classpath\:/static/,classpath\:/public/,file\:${web.upload-path}